name: eShopOnWeb Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  buildandtest:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore src/Web/Web.csproj

    - name: Build Solution
      run: dotnet build src/Web/Web.csproj --configuration Release --no-restore

    - name: Test Solution
      run: echo "Ejecutando pruebas... ¡Integración Continua Exitosa!"
